#!/usr/bin/env bash
# =============================================================================
# Script  : addcert.sh
# Summary : Create RACF keyring and server certificate for Bank of Z.
#           Run once per ZVDT image (called by setup-common.sh).
#
# Liberty (z/OS Connect + frontend) uses the keyring directly:
#   keystoreType="JCERACFKS"
#   keystoreFile="safkeyring://<ZOS_ADMIN_USER>/BOZRING"
#
# The actual server cert (with EKU serverAuth for Safari compliance) is
# generated by gencert-eku.sh using a CSR round-trip:
#   - RACDCERT GENCERT REQONLY  → keypair + CSR (private key stays in RACF)
#   - Bouncy Castle signs the CSR, adds EKU + SANs
#   - RACDCERT IMPORT returns the signed cert to the keyring
# =============================================================================

## CUSTOMIZE ##
userid=${ZOS_ADMIN_USER}
ca_label=${ZOS_CA_LABEL}
ring=BOZRING
label='BoZ'

## FIXED ##
profile=$userid.$ring.LST

# Validate required environment variable
if [[ -z "$userid" ]]; then
  echo "[addcert] FATAL: ZOS_ADMIN_USER is not set" >&2
  exit 1
fi
if [[ -z "$ca_label" ]]; then
  echo "[addcert] FATAL: ZOS_CA_LABEL is not set" >&2
  exit 1
fi

# Step 1: Create the keyring and connect VSICA as the trust anchor.
tsocmd "RACDCERT ID($userid) ADDRING($ring)"
tsocmd "RACDCERT ID($userid) \
 CONNECT(CERTAUTH LABEL('$ca_label') RING($ring) USAGE(CERTAUTH))"
rc=$?
tsocmd "SETROPTS RACLIST(DIGTCERT DIGTRING) REFRESH"

# Step 2: Generate the server cert with EKU serverAuth via Bouncy Castle CSR
# round-trip (gencert-eku.sh).  The private key is generated in RACF and never
# leaves the keyring. Note: gencert-eku.sh removes any existing cert with label
# '$label' from the keyring before generating a fresh one.
if test $rc -eq 0
then
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  if bash "$SCRIPT_DIR/gencert-eku.sh"; then
    echo "[addcert] EKU cert generation succeeded — connecting cert to keyring..."
    tsocmd "RACDCERT ID($userid) \
      CONNECT(LABEL('$label') RING($ring) DEFAULT)"
    rc=$?
    tsocmd "SETROPTS RACLIST(DIGTCERT DIGTRING) REFRESH"
    if test $rc -eq 0; then
      echo "[addcert] Cert '$label' connected to keyring $userid/$ring as DEFAULT"
    else
      echo "[addcert] FATAL: failed to connect cert to keyring $userid/$ring" >&2
    fi
  else
    echo "[addcert] FATAL: gencert-eku.sh failed — Liberty cannot start without a server cert" >&2
    rc=1
  fi
fi

# Step 3: Grant Liberty access to the keyring via RDATALIB
if test $rc -eq 0
then
  tsocmd "RDEFINE RDATALIB $profile"
  tsocmd "PERMIT $profile CLASS(RDATALIB) ID($userid) ACCESS(CONTROL)"
  rc=$?
  tsocmd "SETROPTS RACLIST(RDATALIB) REFRESH"
fi

exit $rc
